version: '3'

services:
  go-wecomchan:
    build: .
    environment:
      - SENDKEY=发送时用来验证的key
      - WECOM_CID=企业微信公司ID
      - WECOM_SECRET=企业微信应用Secret
      - WECOM_AID=企业微信应用ID
      - WECOM_TOUID=@all
    ports:
      - 8080:8080
    restart: unless-stopped
